# Generated by Django 5.0.1 on 2024-01-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_offers_product_image_of_offers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'Novel'), ('P', 'Poem'), ('S', 'Story'), ('O', 'offers')], max_length=2),
        ),
    ]
