# Generated by Django 5.0.1 on 2024-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_offers', models.CharField(default='', max_length=10)),
                ('image_of_offers', models.ImageField(default='', upload_to='offer')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_of_offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_of_offers',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'Novel'), ('P', 'Poem'), ('S', 'Story')], max_length=2),
        ),
    ]
